### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by tseemann** [tothuhien/lsd-0.3beta#1]
Tag here: https://github.com/tothuhien/lsd-0.3beta/releases

eg. `0.3beta`

It's needed for packaging purposes in Brew and Conda.

**Comment by tothuhien** [comment]
thanks tseemann, I didn't know that :), I've just made a release for this

**Comment by tseemann** [comment]
Thanks!

I'll write a `brew` wrapper for it for homebrew-science

**Comment by tothuhien** [comment]
awesome, thanks a lot tseeman.
