### ISSUE TITLE
Try compling with -Wall option

### ISSUE THREAD

**Issue by tseemann** [tothuhien/lsd-0.3beta#2]
There are lots of compiler warnings when compiling with `-Wall`. 

Some of these may be potential bugs.

**Comment by tothuhien** [comment]
ok, thanks, I've checked that. There're indeed some warnings that are due to some redundancies in my code. Fortunately, there's no bugs related to that so far. I'll update the codes soon.

**Comment by tseemann** [comment]
Thanks - i saw a couple of comparisons with unused variables that concerned me (`if (phi < phi2)`) but nothing major.
