### ISSUE TITLE
cannot use a local root optimisation with constraints

### ISSUE THREAD

**Issue by sebastianduchene** [tothuhien/lsd-0.3beta#3]
I am trying to optimise the root position in a certain branch and I would also like to use node constraints, such that the age of every node is equal or smaller than that of its descendants. However, if I combine these two flags:
-r l -c
The  program searches for the root in all branches, as if I was doing -r a -c.

**Comment by tothuhien** [comment]
Is your tree rooted or unrooted? Because option -r l is just used for rooted tree where we search the root position around the given root. If your tree is unrooted, it would search in all branches, so the same as -r a.

**Comment by sebastianduchene** [comment]
My tree is rooted. In fact, I can use ```-r l```, which works fine, but when I do this with -c it still searches for the root in all branches. For example, this works fine:

 ~/Desktop/phylo_programs/lsd-0.3beta-master/bin/lsd_mac -i pruned_clonal_H58.tree -d pruned_clonal_H58.date -r l

But I also want to enforce temporal constraints for the nodes (using the -c flag). Such as:

 ~/Desktop/phylo_programs/lsd-0.3beta-master/bin/lsd_mac -i pruned_clonal_H58.tree -d pruned_clonal_H58.date -r l -c

However, the second command places the root at an entirely different branch.

**Comment by tothuhien** [comment]
It's possible that the rooting function with -c gives different root compared to the one without this option. Because this option is imposed during the root searching, and not after that. I have just tested again -c coupled with -r l, and I think it only searches locally around the given root, maybe just make sure you use the latest version. Cheers.

**Comment by sebastianduchene** [comment]
This is very helpful. Thanks. It turns out that if I specify a non sense root and use the -c option the program searches along several branches. I suppose that these are those which respect the node-age constraints. This makes sense to me now. Out of interest, the data set I was testing this with is attached here, and the commands I was using are:

~/Downloads/lsd-0.3beta-master/bin/lsd_mac -i cholera_misrooted.tree -d cholera.date -r l -c

and 

~/Downloads/lsd-0.3beta-master/bin/lsd_mac -i cholera_misrooted.tree -d cholera.date -r l

The second one only optimises on the branch I specified (I mispecified it on purpose to test this). Thanks again for your quick response!
[cholera_lsd.zip](https://github.com/tothuhien/lsd-0.3beta/files/881422/cholera_lsd.zip)

**Comment by tothuhien** [comment]
Yeah, that's right, searching locally the root uses the hill climbing technique, which just searches for the optimal branches around the given root, and may fail to find the global optimum. It's useful in the case of large trees for saving calculating time and when we are pretty confidence about the root we have and just want to improve it around. If running time is not a problem, then just use "-r a" to search the root on all branches. Thanks for the data. Cheers.
