### ISSUE TITLE
Add % of confidence intervals to documentation

### ISSUE THREAD

**Issue by niemasd** [tothuhien/lsd-0.3beta#5]
I wanted to compute the standard deviation of the mutation rate from the confidence interval output by LSD, but it was not very clear what the % of the confidence interval was. From the LSD paper, it seems like it's 95%? But it would be good to explicitly list this somewhere (e.g. in the `-h` help message, say "95% confidence intervals" instead of just "confidence intervals")

**Comment by tothuhien** [comment]
Hi @niemasd , yes it's true that the confidence interval output from LSD are the 95% interval. I'll put this information in the help message in the next version. Thank you!

**Comment by niemasd** [comment]
Great, thank you!
