### ISSUE TITLE
segmentatin fault with -g 

### ISSUE THREAD

**Issue by fmenardo** [tothuhien/lsd-0.3beta#6]
Hi,

I've run into a problem with the -g option

when I run:
" lsd -i TREE  -d DATES -r a" everything is fine , if I run

" lsd -i TREE  -d DATES -g OUTGROUP_FILE" 

with the same input I get : 

Analyzing outgroups of tree 1 ...
Segmentation fault

The outgroup file looks like this:

1
G00157

and the taxon is present in the tree

Any idea?

Thanks!

**Comment by tothuhien** [comment]
Hi @fmenardo , thanks for reporting this. It's interesting you have this issue while  I normally don't have that with some of my examples. Could you send me via email (tothuhien@gmail.com) your input trees and outgroup files? I'll look at that to see where's the problem. Thanks.
Hien

**Comment by tothuhien** [comment]
Hi @fmenardo, I've found a bug when removing ougroups from the tree. I've fixed it and tried on your data, it seems to work now. Thank for reporting that.
Hien
