### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by tseemann** [tothuhien/lsd-0.3beta#7]
Last release was 0.3-beta but 54 commits since?

**Comment by tothuhien** [comment]
Hi @tseemann , thanks for reminding about that. It's true, I should have made a new release. I'll do that after generating a new executable file for window. I don't have my old windows laptop anymore, should try to figure out how to do that on my new one. Cheers,
Hien

**Comment by tseemann** [comment]
What percent of your users are Windows?  I would have assumed mostly Unix based.

**Comment by tothuhien** [comment]
yeah probably! Anyway I couldn't make a window binary file for now; so I've just updated a new release. Will add that file later. Thanks @tseemann !

**Comment by tseemann** [comment]
Thank you - but I am unable to put it into `brew` because packages with `-beta` in the release name are rejected. Sorry.

**Comment by tothuhien** [comment]
Sorry @tseemann I didn't know about that. I've just removed the pre-release tag beta. Could you please try it again? Thanks a lot for your help.
Hien
