### ISSUE TITLE
input tree - size limit?

### ISSUE THREAD

**Issue by antoine4ucsd** [tothuhien/lsd-0.3beta#9]
Hi
I am trying to run LSD on a very large tree (35k) but I get an error message when loading the tree. I don't have such error with smaller trees. is it a size limit or something else? my tree is unrooted.
Would you have time to take a quick look?
```
lsd
Enter your Input Tree File name> 
All_sequences.newick.txt
Errors in the input trees
```
I also tried with the following but get the same error :
```
lsd -i ./All_sequences.newick.txt -d ./All_sequences.dates4lsd.txt -o ./LSD.output -r a
```

a
[All_sequences.dates4lsd.txt](https://github.com/tothuhien/lsd-0.3beta/files/2911484/All_sequences.dates4lsd.txt)

[All_sequences.newick.txt](https://github.com/tothuhien/lsd-0.3beta/files/2911474/All_sequences.newick.txt)

**Comment by tothuhien** [comment]
Hi @antoine4ucsd , I've tried to run your data on the current version but didn't get that error. It's indeed a very large tree and takes long time to run. But so far, the tree was read and the rooting function is running. Have you recently downloaded the current one on GitHub? Otherwise what's the configuration of computer that you're using? 
Cheers,
Hien

**Comment by antoine4ucsd** [comment]
Thank you Hien
Maybe This is related to the version of LSD I am using...  I will try to update it! I will keep you posted
(Currently working on a Mac.)
Best,
a

**Comment by antoine4ucsd** [comment]
do you have a pre-compiled version of LSD running on mac? I tried running make from within src but I am always having problem with c++/gcc 
```
$ make
g++ -std=c++11 -o confidence_interval.o -c confidence_interval.cpp 
In file included from ~/anaconda2/gcc/include/c++/random:38:0,
                 from confidence_interval.h:1,
                 from confidence_interval.cpp:17:
~/anaconda2/gcc/include/c++/cmath:41:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
make: *** [confidence_interval.o] Error 1
```

**Comment by tothuhien** [comment]
Hi you can try the one in the directory bin:  bin/lsd_mac, it was compiled on my Mac High Sierra.

**Comment by antoine4ucsd** [comment]
it seems to work! thank you ++
a
